version: "3.7"

services:
  # c.f. https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build: .
    command: bash -c "vagrant --version && vagrant plugin list | grep vagrant-aws && vagrant plugin list | grep vagrant-serverspec"
