version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -t vagrant-aws .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar vagrant-aws
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Show docker image size
          command: |
            docker images
            ls -l /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker run -it --rm vagrant-aws bash -c "vagrant --version"
            docker run -it --rm vagrant-aws bash -c "vagrant plugin list"

workflows:
  version: 2

  build:
    jobs:
      - build
