version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -t vagrant-aws .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar vagrant-aws
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Show docker image size
          command: |
            docker images
            ls -l /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker run -it --rm vagrant-aws bash -c "vagrant --version"
            docker run -it --rm vagrant-aws bash -c "vagrant plugin list"

  update_version:
    working_directory: /app
    docker:
      - image: alpine
    steps:
      - run:
          name: Install package
          command: |
            apk --update --no-cache add bash git openssh-client jq curl
      - checkout
      - run:
          name: Setup git
          command: |
            git config push.default current
            git config user.name "CircleCI"
            git config user.email ${EMAIL}
      - run:
          name: Update VERSION
          command: |
            VERSION=`curl -s https://api.github.com/repos/hashicorp/vagrant/tags | jq --raw-output .[0].name | sed -e 's/v//g'`
            echo "VERSION=${VERSION}"
            sed -i -e "s/ENV VAGRANT_VERSION .*$/ENV VAGRANT_VERSION ${VERSION}/g" Dockerfile
            git add Dockerfile

            set +o pipefail
            git commit -m "Bump version ${VERSION} from CircleCI" | true
            git tag -a ${VERSION} -m "Vagrant ${VERSION}" | true
            set -o pipefail

            mkdir -m 700 -p ~/.ssh/
            cat >> ~/.ssh/config << EOF
            StrictHostKeyChecking no
            EOF

            git push origin --tags
            git push origin

workflows:
  version: 2

  build:
    jobs:
      - build

  daily_update:
    triggers:
      - schedule:
          cron: "30 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - update_version
